version: '3.5'
services:

  skeletondb:
    image: postgres:12.2
    restart: always
    container_name: skeleton-db
    environment:
      POSTGRES_PASSWORD: skeletondb
      POSTGRES_USER: skeletondb
      POSTGRES_DB: skeletondb
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data

  skeletonpgadmin:
    image: dpage/pgadmin4:4.19
    container_name: skeleton-pgadmin
    ports:
      - 8005:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin
    depends_on:
      - skeletondb
    restart: always

volumes:
  data: {}
  pgadmin: {}
