version: '3.7'
services:

  skeletondb:
    image: postgres:12.2 # use 12.2 official postgres version
    restart: always
    container_name: skeleton-db
    env_file:
      ./skeleton.env # configure postgres
#    environment:
#      POSTGRES_PASSWORD: skeletondb
#      POSTGRES_USER: skeletondb
#      POSTGRES_DB: jdbc:skeletondb://localhost/skeleton
    ports:
      - "5435:5432"
    volumes:
      - skeleton-data:/var/lib/postgresql/data # persist data even if container shuts down

  skeletonpgadmin:
    image: dpage/pgadmin4:4.19
    container_name: skeleton-pgadmin
    ports:
      - 8005:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin
    depends_on:
      - skeletondb
    restart: always

volumes:
  skeleton-data: {} # named volumes can be managed easier using docker-compose
  pgadmin: {}
