{
 "title": "Akka HTTP - Kamon HTTP",
 "description": "Akka Http via Kamon HTTP",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(akka_http_server_active_requests_sum, job)"
   },
   {
    "name": "operation",
    "label": "operation",
    "query": "label_values(span_processing_time_seconds_sum{job=~\"$job\"}, operation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Processing time 95 percentile $operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(span_processing_time_seconds_bucket{operation=~\"$operation\"}[5m])) by (le,operation,span_kind,error)) ",
     "legendFormat": "error = {{error}}"
    }
   ]
  },
  {
   "title": "Requests coming to $operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(span_processing_time_seconds_count{operation=~\"$operation\"}[2m])) by (operation,span_kind,error)",
     "legendFormat": "error = {{error}}"
    }
   ]
  },
  {
   "title": "Open connections to all instances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, port) (irate(akka_http_server_open_connections_sum{job=~\"$job\"}[2m]) / irate(akka_http_server_open_connections_count{job=~\"$job\"}[2m]))"
    }
   ]
  },
  {
   "title": "Active requests rate to all instances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job)(irate(akka_http_server_active_requests_sum{job=~\"$job\"}[2m]) / irate(akka_http_server_active_requests_count{job=~\"$job\"}[2m]))"
    }
   ]
  }
 ]
}